export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_UNSUCCESS = "LOGIN_UNSUCCESS";
export const LOGOUT = "LOGOUT";


export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const POST_USER_SUCCESS = "POST_USER_SUCCESS";
export const PUT_USER_SUCCESS = "PUT_USER_SUCCESS";
export const GET_USERS_SUCCESS = "GET_USERS_SUCCESS";
export const DELETE_USER_UNSUCCESS = "DELETE_USER_UNSUCCESS";
export const DELETE_USERS_UNSUCCESS = "DELETE_USERS_UNSUCCESS";
export const POST_USER_UNSUCCESS = "POST_USER_UNSUCCESS";
export const PUT_USER_UNSUCCESS = "PUT_USER_UNSUCCESS";
export const GET_USERS_UNSUCCESS = "GET_USERS_UNSUCCESS";
export const CLOSE_USERS_RESPONSE = "CLOSE_USERS_RESPONSE";

export const DELETE_ROOM_SUCCESS = "DELETE_ROOM_SUCCESS";
export const DELETE_ROOMS_SUCCESS = "DELETE_ROOM_SUCCESS";
export const POST_ROOM_SUCCESS = "POST_ROOM_SUCCESS";
export const PUT_ROOM_SUCCESS = "PUT_ROOM_SUCCESS";
export const GET_ROOMS_SUCCESS = "GET_ROOMS_SUCCESS";
export const DELETE_ROOM_UNSUCCESS = "DELETE_ROOM_UNSUCCESS";
export const DELETE_ROOMS_UNSUCCESS = "DELETE_ROOM_UNSUCCESS";
export const POST_ROOM_UNSUCCESS = "POST_ROOM_UNSUCCESS";
export const PUT_ROOM_UNSUCCESS = "PUT_ROOM_UNSUCCESS";
export const GET_ROOMS_UNSUCCESS = "GET_ROOMS_UNSUCCESS";
export const CLOSE_ROOMS_RESPONSE = "CLOSE_ROOMS_RESPONSE";